//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUAN1_CS
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGKE
    {
        public int id { get; set; }
        public Nullable<int> ngay { get; set; }
        public Nullable<int> thang { get; set; }
        public Nullable<int> nam { get; set; }
        public Nullable<double> doanhThuThucTe { get; set; }
        public Nullable<double> doanhThuHeThong { get; set; }
        public string manv { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
